import type { PayrollAnomaly } from "@/lib/domain/types";

export const demoAnomalies: PayrollAnomaly[] = [
  {
    id: "anom_missing_tax_card",
    employeeId: "emp_07",
    severity: "critical",
    type: "missing_tax_card",
    title: "Missing tax card data",
    explanation:
      "The employee is included in the May payroll draft, but the current tax card import is missing.",
    evidence: "April had a populated tax card; the May import returned an empty tax reference.",
    suggestedNextAction: "Request the updated tax card before approving the payroll run.",
    status: "open",
    previousMonthContext: "April tax card values were present and matched the expected rate.",
    blockingApproval: true,
  },
  {
    id: "anom_tulorekisteri_validation",
    employeeId: "emp_13",
    severity: "critical",
    type: "tulorekisteri_validation",
    title: "Tulorekisteri validation failed",
    explanation:
      "One payroll record does not satisfy the demo validation rules used for the reporting export.",
    evidence: "The record is missing a required employment tag and the report export rejected it.",
    suggestedNextAction: "Correct the payroll export fields and rerun validation.",
    status: "open",
    previousMonthContext: "The April export passed validation without manual intervention.",
    blockingApproval: true,
  },
  {
    id: "anom_net_salary_change",
    employeeId: "emp_01",
    severity: "warning",
    type: "net_salary_change",
    title: "Net salary changed sharply",
    explanation:
      "The current net salary is noticeably higher than the previous month after a one-off bonus rolled off.",
    evidence: "Net pay moved +12% compared with the April payroll snapshot.",
    suggestedNextAction: "Confirm that the change is expected before sending the payroll onward.",
    status: "waiting_for_customer",
    previousMonthContext: "April included a temporary project bonus that is absent in May.",
    blockingApproval: false,
  },
  {
    id: "anom_missing_working_hours",
    employeeId: "emp_02",
    severity: "warning",
    type: "missing_working_hours",
    title: "Missing working hours entry",
    explanation:
      "The hourly employee has an incomplete time sheet for the final week of the payroll period.",
    evidence: "The May timesheet stops at 2026-05-28 and the last two shifts are unconfirmed.",
    suggestedNextAction: "Ask the customer to provide the missing shift hours.",
    status: "waiting_for_customer",
    previousMonthContext: "April time tracking was complete and approved on the first pass.",
    blockingApproval: true,
  },
  {
    id: "anom_absence_affects_salary",
    employeeId: "emp_04",
    severity: "warning",
    type: "absence_affects_salary",
    title: "Absence changes salary calculation",
    explanation:
      "An unpaid absence intersects with the salary window and changes the final amount due.",
    evidence: "The demo absence ledger shows a three-day unpaid leave overlapping the pay period.",
    suggestedNextAction: "Verify the absence dates and confirm the salary adjustment rule.",
    status: "waiting_for_customer",
    previousMonthContext: "April had a shorter leave and the adjustment was manually approved.",
    blockingApproval: true,
  },
  {
    id: "anom_missing_lunch_benefit",
    employeeId: "emp_09",
    severity: "info",
    type: "missing_lunch_benefit",
    title: "Lunch benefit missing from one employee",
    explanation:
      "A lunch benefit line is missing for one salaried employee in this payroll draft.",
    evidence: "The benefit import included the team, but this employee was skipped in the latest batch.",
    suggestedNextAction: "Confirm whether the employee opted out or if the benefit import is incomplete.",
    status: "ignored",
    previousMonthContext: "The benefit was present in April and the employee remained eligible.",
    blockingApproval: false,
  },
  {
    id: "anom_final_salary_checklist_incomplete",
    employeeId: "emp_15",
    severity: "info",
    type: "final_salary_checklist_incomplete",
    title: "Final salary checklist is incomplete",
    explanation:
      "The salary checklist is missing one supporting confirmation before final approval.",
    evidence: "The run notes still show one unresolved checklist entry for the final approval pass.",
    suggestedNextAction: "Complete the checklist item and record the approval evidence.",
    status: "message_drafted",
    previousMonthContext: "April's checklist was completed after a final review round.",
    blockingApproval: true,
  },
];

