import type { EmployeeRecord } from "@/lib/domain/types";

export const demoEmployees: EmployeeRecord[] = [
  {
    id: "emp_01",
    fullName: "Aino Korhonen",
    roleTitle: "Payroll Specialist",
    employmentType: "monthly",
    team: "Finance",
  },
  {
    id: "emp_02",
    fullName: "Mikko Lahtinen",
    roleTitle: "Warehouse Operator",
    employmentType: "hourly",
    team: "Logistics",
  },
  {
    id: "emp_03",
    fullName: "Sanna Miettinen",
    roleTitle: "HR Coordinator",
    employmentType: "monthly",
    team: "People Ops",
  },
  {
    id: "emp_04",
    fullName: "Jari Salonen",
    roleTitle: "Maintenance Technician",
    employmentType: "hourly",
    team: "Facilities",
  },
  {
    id: "emp_05",
    fullName: "Elina Nieminen",
    roleTitle: "Sales Support Specialist",
    employmentType: "monthly",
    team: "Customer Care",
  },
  {
    id: "emp_06",
    fullName: "Joonas Lehto",
    roleTitle: "Delivery Driver",
    employmentType: "hourly",
    team: "Logistics",
  },
  {
    id: "emp_07",
    fullName: "Tiina Kallio",
    roleTitle: "Accounts Assistant",
    employmentType: "monthly",
    team: "Finance",
  },
  {
    id: "emp_08",
    fullName: "Petri Hakanen",
    roleTitle: "Production Operator",
    employmentType: "hourly",
    team: "Manufacturing",
  },
  {
    id: "emp_09",
    fullName: "Laura Heikkinen",
    roleTitle: "Team Lead, Customer Care",
    employmentType: "monthly",
    team: "Customer Care",
  },
  {
    id: "emp_10",
    fullName: "Ville Rantala",
    roleTitle: "Shift Supervisor",
    employmentType: "hourly",
    team: "Manufacturing",
  },
  {
    id: "emp_11",
    fullName: "Heli Mäkinen",
    roleTitle: "Compensation Analyst",
    employmentType: "monthly",
    team: "People Ops",
  },
  {
    id: "emp_12",
    fullName: "Oskari Virtanen",
    roleTitle: "Support Technician",
    employmentType: "hourly",
    team: "IT Services",
  },
  {
    id: "emp_13",
    fullName: "Marja Saari",
    roleTitle: "Billing Specialist",
    employmentType: "monthly",
    team: "Finance",
  },
  {
    id: "emp_14",
    fullName: "Kari Vuorinen",
    roleTitle: "Forklift Operator",
    employmentType: "hourly",
    team: "Logistics",
  },
  {
    id: "emp_15",
    fullName: "Anni Aho",
    roleTitle: "Office Coordinator",
    employmentType: "monthly",
    team: "Operations",
  },
  {
    id: "emp_16",
    fullName: "Roope Koskinen",
    roleTitle: "Picker-Packer",
    employmentType: "hourly",
    team: "Warehouse",
  },
  {
    id: "emp_17",
    fullName: "Eveliina Koski",
    roleTitle: "Quality Specialist",
    employmentType: "monthly",
    team: "Quality",
  },
  {
    id: "emp_18",
    fullName: "Tuomas Hämäläinen",
    roleTitle: "Machine Operator",
    employmentType: "hourly",
    team: "Manufacturing",
  },
];

